version: '4'
services:
  container:
    image: bitcurator/bitcurator:jammy
    hostname: bitcurator
    container_name: bitcurator
    networks:
      net:
        ipv4_address: 172.22.0.3
    volumes:
      - <your_volume_here>:/home/bcadmin/files/:ro
    ports:
      - "33:22"
    cap_add:
      - SYS_ADMIN
      - MKNOD
    privileged: true
    devices:
      - "/dev/fuse:/dev/fuse"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
